# form settings
FORM_TITLE = ""
FONT = "Calibri"
TERMINAL_FONT = "Consolas"
MAIN_TEXT_SIZE = 150
BUTTON_FONT_SIZE = 22
LABEL_FONT_SIZE = 18
TERMINAL_LABEL_FONT_SIZE = 14
LABEL_WRAPLENGTH = 120
BUTTON_CORNER_RADIUS = 10
FRAME_CORNER_RADIUS = 6

# #RRGGBB: Red Green Blue
APP_PURPLE = "#752157"
APP_LIGHT_PURPLE = "#974379"
APP_DARK_PURPLE = "#060000"
LIGHT_GREEN = "#90FF90"
GREEN = "#00FF00"
DARK_GREEN = "#007000"
WHITE = "#F2F2F2"
BLACK = "#1F1F1F"
LIGHT_GRAY = "#C0C0C0"
GRAY = "#D0D0D0"
DARK_GRAY = "#303030"
LIGHT_RED = "#FF9090"
RED = "#FF0000"
DARK_RED = "#707000"

CTK_COLOR = (WHITE, APP_DARK_PURPLE)
FRAME_FG_COLOR = "transparent"
LABEL_TEXT_COLOR = (BLACK, LIGHT_GRAY)
TERMINAL_BG_COLOR = (GRAY, BLACK)
BUTTON_TEXT_COLOR = (BLACK, WHITE)
BUTTON_FG_COLOR = (LIGHT_GRAY, DARK_GRAY)
BUTTON_FG_COLOR_TRUE = (LIGHT_GREEN, DARK_GREEN)
BUTTON_FG_COLOR_FALSE = (LIGHT_RED, DARK_RED)
BUTTON_HOVER_COLOR = (GRAY, GRAY)
BUTTON_HOVER_COLOR_TRUE = (GREEN, GREEN)
BUTTON_HOVER_COLOR_RED = (RED, RED)

import os
WORKSPACE_PATH = os.getcwd()
LOGO_FOLDER_PATH = rf"{WORKSPACE_PATH}\images"

# image settings
IMG_LOGO_APP = rf"{WORKSPACE_PATH}\logo\APP_Logo.png"
IMG_LOGO_APP_ICON = rf"{WORKSPACE_PATH}\logoAPP_Logo_icon.png"
